import random
import math
from typing import List, Callable

def df1_problem_generator(
        n_dimensions: int,
        n_peaks: int,
        h_base: float,
        h_range: float,
        r_base: float,
        r_range: float
) -> Callable[[List[float]], float]:
    H = [h_base + random.random() * h_range for _ in range(n_peaks)]
    R = [r_base + random.random() * r_range for _ in range(n_peaks)]
    X = [[random.uniform(-1,1) for _ in range(n_dimensions)] for _ in range(n_peaks)]

    def f(x: List[float]) -> float:
        if len(x) != n_dimensions:
            raise ValueError(f"Input vector x must have {n_dimensions} dimensions.")
        
        peak_values = []
        for i in range(n_peaks):
            sum_sq_diff = sum((x[j] - X[i][j]) ** 2 for j in range(n_dimensions))
            value = H[i] - R[i] * math.sqrt(sum_sq_diff)
            peak_values.append(value)

        return max(peak_values)
    
    return f

def example_usage() -> None:
    n_dimensions = 5
    n_peaks = 10
    height_base = 30.0
    height_range = 40.0
    slope_base = 0.1
    slope_range = 0.2

    df1_function = df1_problem_generator(
        n_dimensions,
        n_peaks,
        height_base,
        height_range,
        slope_base,
        slope_range
    )

    sol = [random.uniform(-1,1) for _ in range(n_dimensions)]

    fitness = df1_function(sol)

    print(f"Number of Dimensions: {n_dimensions}")
    print(f"Candidate Solution: {sol}")
    print(f"Calculated Fitness: {fitness}")

import matplotlib.pyplot as plt
import numpy as np

def one_d_viz() -> None:
    """
    Visualize the funciton generated by df1_problem_generator() for one
    dimension
    """
    df1 = df1_problem_generator(
        n_dimensions=1,
        n_peaks=5,
        h_base=30.0,
        h_range=40.0,
        r_base=0.1,
        r_range=0.2
    )

    # Evaluate the function on a grid of x-values
    x_vals = np.linspace(-1, 1, 500)
    y_vals = [df1([x]) for x in x_vals]

    # Plot the result
    plt.plot(x_vals, y_vals)
    plt.title("DF1 Landscape (1D)")
    plt.xlabel("x")
    plt.ylabel("f(x)")
    plt.grid(True)
    plt.show()


from mpl_toolkits.mplot3d import Axes3D

def two_d_viz() -> None:
    """
    Visualize the funciton generated by df1_problem_generator() for two
    dimensions
    """
    df1 = df1_problem_generator(
        n_dimensions=2,
        n_peaks=10,
        h_base=30.0,
        h_range=40.0,
        r_base=0.1,
        r_range=0.2
    )

    # Create a mesh grid in [-1, 1] x [-1, 1]
    x = np.linspace(-1, 1, 100)
    y = np.linspace(-1, 1, 100)
    X, Y = np.meshgrid(x, y)
    Z = np.array([[df1([x_val, y_val]) for x_val in x] for y_val in y])

    # Surface plot
    fig = plt.figure(figsize=(12, 5))

    ax1 = fig.add_subplot(1, 2, 1, projection='3d')
    ax1.plot_surface(X, Y, Z, cmap='viridis', edgecolor='none')
    ax1.set_title("DF1 Landscape (2D Surface)")
    ax1.set_xlabel("x")
    ax1.set_ylabel("y")
    ax1.set_zlabel("f(x, y)")

    # Contour plot
    ax2 = fig.add_subplot(1, 2, 2)
    contour = ax2.contourf(X, Y, Z, levels=50, cmap='viridis')
    fig.colorbar(contour, ax=ax2)
    ax2.set_title("DF1 Landscape (2D Contour)")
    ax2.set_xlabel("x")
    ax2.set_ylabel("y")

    plt.tight_layout()
    plt.show()

if __name__ == '__main__':
    # example_usage()
    # one_d_viz()
    two_d_viz()
